version: '3'
services:
  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.5
  # server:
  #   build:
  #     context: ./server
  #   ports:
  #     - "5000:5000"
  # client: 
  #   build:
  #     context: ./client
  #   ports:
  #     - "3000:3000"